import React from 'react';
import { Upload, Brain, Sparkles, GraduationCap, ArrowRight } from 'lucide-react';
import './styles/HowItWorks.css'

const HowItWorks = () => {
  const steps = [
    {
      icon: Upload,
      number: 1,
      title: "Upload Your Content",
      description: "Record lectures live or upload PDFs, videos, audio files, and documents. Works with any format you need."
    },
    {
      icon: Brain,
      number: 2,
      title: "Let AI Process",
      description: "Our AI transcribes and analyzes your content, identifying key concepts and creating structured editable notes."
    },
    {
      icon: Sparkles,
      number: 3,
      title: "Get Study Materials",
      description: "Receive comprehensive notes, flashcards, quizzes, and podcasts tailored to your learning needs.",
      link: {
        text: "Over 15 million notes",
        url: "/blog/october-2025-announcement-5-million-users"
      }
    },
    {
      icon: GraduationCap,
      number: 4,
      title: "Study & Succeed",
      description: "Access materials anywhere, share with classmates, and use built-in study modes to ace your exams. Turbo works on both web and mobile - use both!"
    }
  ];

  const stats = [
    { value: "5M+", label: "Active Students" },
    { value: "99%", label: "Accuracy Rate" },
    { value: "30s", label: "Processing Time" }
  ];

  return (
    <div className="how-it-works">
      <div className="how-it-works__container">
        {/* Header */}
        <div className="how-it-works__header">
          <h2 id="how-it-works-heading" className="how-it-works__title">
            How It Works - It's Simple.
          </h2>
          <p className="how-it-works__subtitle">
            Transform any PDF, YouTube video, or audio into beautiful notes and study tools in four simple steps.
          </p>
        </div>

        {/* Steps Grid */}
        <div className="how-it-works__steps">
          {steps.map((step, index) => {
            const Icon = step.icon;
            return (
              <div key={step.number} className="step">
                <div className="step__content">
                  <div className="step__icon-wrapper">
                    <div className="step__icon-circle">
                      <Icon className="step__icon" />
                    </div>
                    <div className="step__number">{step.number}</div>
                  </div>
                  <h3 className="step__title">{step.title}</h3>
                  <p className="step__description">
                    {step.description}
                    {step.link && (
                      <>
                        {' '}
                        <a href={step.link.url} className="step__link">
                          {step.link.text}
                        </a>
                        {' have been generated by students on Turbo.'}
                      </>
                    )}
                  </p>
                </div>
                {index < steps.length - 1 && (
                  <div className="step__connector" />
                )}
              </div>
            );
          })}
        </div>

        {/* Stats */}
        <div className="how-it-works__stats">
          <div className="stats">
            {stats.map((stat, index) => (
              <React.Fragment key={stat.label}>
                <div className="stat">
                  <p className="stat__value">{stat.value}</p>
                  <p className="stat__label">{stat.label}</p>
                </div>
                {index < stats.length - 1 && <div className="stat__divider" />}
              </React.Fragment>
            ))}
          </div>
        </div>

        {/* CTA Card */}
        <div className="how-it-works__cta">
          <a href="/for-students" className="cta-card">
            <div className="cta-card__content">
              <div className="cta-card__text">
                <span className="cta-card__badge">Built for Students</span>
                <h3 className="cta-card__title">Explore All Student Features</h3>
                <p className="cta-card__description">
                  Learn how to record lectures, organize notes in folders, generate flashcards from any PDF, and create quizzes that actually help you study. See every feature built specifically for students.
                </p>
              </div>
              <div className="cta-card__arrow">
                <ArrowRight className="arrow-icon" />
              </div>
            </div>
            <div className="cta-card__glow cta-card__glow--top" />
            <div className="cta-card__glow cta-card__glow--bottom" />
          </a>
        </div>
      </div>
    </div>
  );
};

export default HowItWorks;